"""message

Revision ID: fd62dc0f7f74
Revises: 8df54554e47b
Create Date: 2025-02-01 16:07:46.345744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd62dc0f7f74'
down_revision = '8df54554e47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
